"""Demo dataset for Renovation OS: a ~135k renovation of a 1970s semi-detached house.

Frozen on AS_OF so every alert type, the overpayment flag, a pending change order,
a hidden-cost quote upset and an over-budget forecast are all visible.
Used by build_renovation_os.py (to fill the DEMO workbook) and by test_workbook.py
(to compute expected dashboard values independently of the spreadsheet formulas).
"""
from datetime import date as D

AS_OF = D(2026, 6, 15)

SETUP = dict(
    name="Maple Lane Renovation",
    address="12 Maple Lane",
    start=D(2026, 3, 2),
    target=D(2026, 8, 21),
    total_budget=135000,
    area_m2=142,
    contingency=0.10,
    alert_days=7,
    decide_buf=7,
    order_buf=5,
    overpay_tol=0.10,
)

# Default categories (also prefilled in BLANK) with demo budget / stage.
CATEGORIES = [
    ("Demolition", 4000, "Complete"),
    ("Structural", 9000, "Complete"),
    ("Plumbing", 9500, "Contracted"),
    ("Electrical", 10000, "Contracted"),
    ("HVAC", 9000, "Contracted"),
    ("Windows & doors", 12000, "Contracted"),
    ("Roofing", 3000, "Estimating"),
    ("Kitchen", 20000, "Contracted"),
    ("Bathrooms", 15000, "Contracted"),
    ("Flooring", 8500, "Estimating"),
    ("Painting", 4500, "Estimating"),
    ("Landscaping", 2000, "Estimating"),
    ("Furniture", 3000, "Estimating"),
    ("Appliances", 3500, "Estimating"),
    ("Permits", 1500, "Complete"),
    ("Professional fees", 5000, "Contracted"),
    ("Waste removal", 1500, "Estimating"),
    ("Other", 500, "Estimating"),
]

# name, area m2, budget
ROOMS = [
    ("Kitchen", 18, 25000),
    ("Bathroom 1", 7, 17000),
    ("Bathroom 2", 5, 8000),
    ("Master bedroom", 16, 4000),
    ("Living room", 32, 15000),
    ("Exterior", None, 4000),
    ("Custom room 7", None, None),
    ("Custom room 8", None, None),
    ("Custom room 9", None, None),
    ("Custom room 10", None, None),
]
BLANK_ROOM_NAMES = ["Kitchen", "Bathroom 1", "Bathroom 2", "Master bedroom", "Living room",
                    "Exterior", "Custom room 7", "Custom room 8", "Custom room 9",
                    "Custom room 10"]

CONTRACTORS = [
    dict(company="Hansen Demolition", trade="Demolition & strip-out", cat="Demolition",
         room="Whole house", contact="Lars Hansen", phone="+31 6 1234 5678",
         email="lars@hansen-demo.example", value=3800, signed="Yes", start=D(2026, 4, 20),
         end=D(2026, 4, 29), insured="Yes", licensed="Yes", warranty=1, work=1.0),
    dict(company="Solid Structures Ltd", trade="Builder / structural", cat="Structural",
         room="Living room", contact="Maria Costa", phone="+31 6 2345 6789",
         email="maria@solidstructures.example", value=9400, signed="Yes", start=D(2026, 4, 30),
         end=D(2026, 5, 11), insured="Yes", licensed="Yes", warranty=10, work=1.0),
    dict(company="FlowRight Plumbing", trade="Plumbing", cat="Plumbing", room="Whole house",
         contact="Tom de Vries", phone="+31 6 3456 7890", email="tom@flowright.example",
         value=9200, signed="Yes", start=D(2026, 5, 12), end=D(2026, 6, 5), insured="Yes",
         licensed="Yes", warranty=2, work=0.6),
    dict(company="Bright Spark Electric", trade="Electrical", cat="Electrical",
         room="Whole house", contact="Ahmed Karimi", phone="+31 6 4567 8901",
         email="ahmed@brightspark.example", value=10500, signed="Yes", start=D(2026, 5, 12),
         end=D(2026, 6, 15), insured="Yes", licensed="No", warranty=2, work=0.35),
    dict(company="ClimaHeat HVAC", trade="Heat pump & ventilation", cat="HVAC",
         room="Whole house", contact="Eva Jansen", phone="+31 6 5678 9012",
         email="eva@climaheat.example", value=9300, signed="Yes", start=D(2026, 6, 6),
         end=D(2026, 6, 15), insured="Yes", licensed="Yes", warranty=5, work=0.25),
    dict(company="ClearView Windows", trade="Windows & doors", cat="Windows & doors",
         room="Whole house", contact="Pieter Smit", phone="+31 6 6789 0123",
         email="pieter@clearview.example", value=12400, signed="Yes", start=D(2026, 4, 30),
         end=D(2026, 5, 7), insured="Yes", licensed="Yes", warranty=10, work=0.9),
    dict(company="Nordic Kitchens", trade="Kitchen supply & install", cat="Kitchen",
         room="Kitchen", contact="Sofie Berg", phone="+31 6 7890 1234",
         email="sofie@nordickitchens.example", value=19400, signed="Yes", start=D(2026, 7, 2),
         end=D(2026, 7, 13), insured="Yes", licensed="Yes", warranty=5, work=0.0),
    dict(company="Aqua Bath Studio", trade="Bathroom fit-out", cat="Bathrooms",
         room="Bathroom 1", contact="Luca Romano", phone="+31 6 8901 2345",
         email="luca@aquabath.example", value=11200, signed="Yes", start=D(2026, 7, 2),
         end=D(2026, 7, 26), insured="Yes", licensed="Yes", warranty=5, work=0.0),
    dict(company="GreenPlan Architects", trade="Architect & permits", cat="Professional fees",
         room="Whole house", contact="Nina Visser", phone="+31 6 9012 3456",
         email="nina@greenplan.example", value=4800, signed="Yes", start=D(2026, 3, 2),
         end=D(2026, 8, 14), insured="Yes", licensed="Yes", warranty=0, work=0.75),
    dict(company="Finish Line Painters", trade="Painting & decorating", cat="Painting",
         room="Whole house", contact="Johan Bakker", phone="+31 6 0123 4567",
         email="johan@finishline.example", value=4700, signed="No", insured="Yes",
         licensed="Yes", warranty=2, work=0.0),
    dict(company="Oak & Plank Flooring", trade="Flooring", cat="Flooring", room="Whole house",
         contact="Mila Peters", phone="+31 6 1122 3344", email="mila@oakplank.example",
         signed="No", insured="Yes", licensed="Yes", warranty=10),
]

COMM_LOG = [
    dict(who="Bright Spark Electric", date=D(2026, 6, 2),
         summary="Asked for revised schedule after 1-week slip — no reply yet", fu="Yes",
         fu_date=D(2026, 6, 10), done="No"),
    dict(who="Oak & Plank Flooring", date=D(2026, 6, 12),
         summary="Quote received; asked them to include skirting boards", fu="Yes",
         fu_date=D(2026, 6, 18), done="No"),
    dict(who="Nordic Kitchens", date=D(2026, 5, 28),
         summary="Confirmed install start 2 July, delivery 1 July", fu="No"),
    dict(who="FlowRight Plumbing", date=D(2026, 6, 9),
         summary="Pipe re-routing caused delay; rough-in now late", fu="Yes",
         fu_date=D(2026, 6, 1), done="Yes"),
]

# party, milestone, room, cat_in, pct, fixed, due, inv_no, inv_date, inv_amt, paid_date, paid_amt
PAYMENTS = [
    dict(party="GreenPlan Architects", milestone="Design package 50%", pct=0.5,
         due_date=D(2026, 3, 25), inv_no="GP-01", inv_date=D(2026, 3, 20), inv_amt=2400,
         paid_date=D(2026, 3, 24), paid_amt=2400),
    dict(party="City Building Dept", milestone="Building permit fee", cat_in="Permits",
         fixed=1350, due_date=D(2026, 3, 30), inv_no="PERMIT-2026-114",
         inv_date=D(2026, 3, 25), inv_amt=1350, paid_date=D(2026, 3, 28), paid_amt=1350),
    dict(party="GreenPlan Architects", milestone="Permit approved 25%", pct=0.25,
         due_date=D(2026, 4, 22), inv_no="GP-02", inv_date=D(2026, 4, 20), inv_amt=1200,
         paid_date=D(2026, 4, 21), paid_amt=1200),
    dict(party="ClearView Windows", milestone="Order 40%", pct=0.4, due_date=D(2026, 4, 10),
         inv_no="CV-311", inv_date=D(2026, 4, 6), inv_amt=4960, paid_date=D(2026, 4, 9),
         paid_amt=4960),
    dict(party="Hansen Demolition", milestone="Deposit 30%", pct=0.3, due_date=D(2026, 4, 15),
         inv_no="H-101", inv_date=D(2026, 4, 10), inv_amt=1140, paid_date=D(2026, 4, 14),
         paid_amt=1140),
    dict(party="City Skips", milestone="Skip hire (2 skips)", cat_in="Waste removal",
         fixed=640, due_date=D(2026, 4, 22), inv_no="CS-88", inv_date=D(2026, 4, 20),
         inv_amt=640, paid_date=D(2026, 4, 22), paid_amt=640),
    dict(party="Solid Structures Ltd", milestone="Deposit 30%", pct=0.3,
         due_date=D(2026, 4, 25), inv_no="SS-12", inv_date=D(2026, 4, 21), inv_amt=2820,
         paid_date=D(2026, 4, 24), paid_amt=2820),
    dict(party="Hansen Demolition", milestone="Completion 70%", pct=0.7,
         due_date=D(2026, 5, 5), inv_no="H-107", inv_date=D(2026, 4, 30), inv_amt=2660,
         paid_date=D(2026, 5, 4), paid_amt=2660),
    dict(party="Bright Spark Electric", milestone="Deposit 30%", pct=0.3,
         due_date=D(2026, 5, 8), inv_no="BS-2026-04", inv_date=D(2026, 5, 4), inv_amt=3150,
         paid_date=D(2026, 5, 7), paid_amt=3150),
    dict(party="FlowRight Plumbing", milestone="Start of works 30%", pct=0.3,
         due_date=D(2026, 5, 12), inv_no="FR-5501", inv_date=D(2026, 5, 8), inv_amt=2760,
         paid_date=D(2026, 5, 11), paid_amt=2760),
    dict(party="Nordic Kitchens", milestone="Deposit 10%", room="Kitchen", pct=0.1,
         due_date=D(2026, 5, 15), inv_no="NK-778", inv_date=D(2026, 5, 11), inv_amt=1940,
         paid_date=D(2026, 5, 14), paid_amt=1940),
    dict(party="ClearView Windows", milestone="Installation 50%", pct=0.5,
         due_date=D(2026, 5, 15), inv_no="CV-340", inv_date=D(2026, 5, 8), inv_amt=6200,
         paid_date=D(2026, 5, 14), paid_amt=6200),
    dict(party="Solid Structures Ltd", milestone="Completion 70%", pct=0.7,
         due_date=D(2026, 5, 20), inv_no="SS-19", inv_date=D(2026, 5, 12), inv_amt=6580,
         paid_date=D(2026, 5, 19), paid_amt=6580),
    dict(party="Solid Structures Ltd", milestone="Change order CO-1 (steel beam)",
         fixed=1200, due_date=D(2026, 5, 25), inv_no="SS-20", inv_date=D(2026, 5, 18),
         inv_amt=1200, paid_date=D(2026, 5, 25), paid_amt=1200),
    dict(party="Bright Spark Electric", milestone="First fix 30%", pct=0.3,
         due_date=D(2026, 6, 1), inv_no="BS-2026-07", inv_date=D(2026, 5, 26), inv_amt=3150,
         paid_date=D(2026, 5, 30), paid_amt=3150),
    dict(party="ClimaHeat HVAC", milestone="Equipment 30%", pct=0.3, due_date=D(2026, 6, 5),
         inv_no="CH-90", inv_date=D(2026, 6, 1), inv_amt=2790, paid_date=D(2026, 6, 4),
         paid_amt=2790),
    dict(party="FlowRight Plumbing", milestone="Rough-in complete 40%", pct=0.4,
         due_date=D(2026, 6, 10), inv_no="FR-5534", inv_date=D(2026, 6, 1), inv_amt=3680),
    dict(party="Aqua Bath Studio", milestone="Deposit 20%", pct=0.2, due_date=D(2026, 6, 19),
         inv_no="ABS-301", inv_date=D(2026, 6, 12), inv_amt=2240),
    dict(party="ClearView Windows", milestone="Final 10% (after snagging)", pct=0.1,
         due_date=D(2026, 6, 20), inv_no="CV-362", inv_date=D(2026, 6, 12), inv_amt=1240),
    dict(party="TileDepot", milestone="Bathroom 1 tiles", room="Bathroom 1",
         cat_in="Bathrooms", fixed=1450, due_date=D(2026, 6, 15), inv_no="TD-4471",
         inv_date=D(2026, 6, 12), inv_amt=1450, paid_date=D(2026, 6, 15), paid_amt=1450),
    dict(party="StoneWorks", milestone="Quartz worktop", room="Kitchen", cat_in="Kitchen",
         fixed=2450, due_date=D(2026, 6, 25)),
    dict(party="Nordic Kitchens", milestone="Delivery 50%", room="Kitchen", pct=0.5,
         due_date=D(2026, 6, 29)),
    dict(party="ClimaHeat HVAC", milestone="Commissioning 70%", pct=0.7,
         due_date=D(2026, 6, 30)),
    dict(party="FlowRight Plumbing", milestone="Final 30%", pct=0.3, due_date=D(2026, 7, 20)),
    dict(party="Nordic Kitchens", milestone="Completion 40%", room="Kitchen", pct=0.4,
         due_date=D(2026, 7, 20)),
    dict(party="Aqua Bath Studio", milestone="Completion 80%", pct=0.8,
         due_date=D(2026, 7, 31)),
    dict(party="Bright Spark Electric", milestone="Final 40%", pct=0.4,
         due_date=D(2026, 8, 12)),
    dict(party="GreenPlan Architects", milestone="Final sign-off 25%", pct=0.25,
         due_date=D(2026, 8, 20)),
]

CHANGE_ORDERS = [
    dict(no="CO-1", date=D(2026, 5, 2), req="Contractor", contractor="Solid Structures Ltd",
         cat="Structural", room="Living room",
         desc="Heavier steel beam required by structural engineer",
         reason="Unforeseen condition", cost=1200, days=2, status="Approved",
         dec_date=D(2026, 5, 3)),
    dict(no="CO-2", date=D(2026, 5, 20), req="Owner", contractor="Nordic Kitchens",
         cat="Kitchen", room="Kitchen", desc="Add pantry cabinet + soft-close upgrade",
         reason="Client choice", cost=900, days=0, status="Approved", dec_date=D(2026, 5, 22)),
    dict(no="CO-3", date=D(2026, 5, 25), req="Contractor", contractor="ClearView Windows",
         cat="Windows & doors", room="Living room",
         desc="Upgrade sliding door to triple glazing", reason="Client choice", cost=2100,
         days=5, status="Rejected", dec_date=D(2026, 5, 28)),
    dict(no="CO-4", date=D(2026, 6, 1), req="Owner", contractor="Aqua Bath Studio",
         cat="Bathrooms", room="Bathroom 1", desc="Electric underfloor heating in bathroom 1",
         reason="Client choice", cost=1650, days=1, status="Approved", dec_date=D(2026, 6, 3)),
    dict(no="CO-5", date=D(2026, 6, 9), req="Contractor", contractor="Bright Spark Electric",
         cat="Electrical", room="Whole house", desc="EV charger + 6 extra circuits",
         reason="Client choice", cost=3400, days=5, status="Pending"),
]

# id is the row order (1-based). pred refers to an earlier id.
TASKS = [
    dict(phase="Pre-construction", task="Design & plans", room="Whole house",
         contractor="GreenPlan Architects", dur=21, status="Done", done_date=D(2026, 3, 20)),
    dict(phase="Pre-construction", task="Building permit", room="Whole house",
         contractor="GreenPlan Architects", dur=28, pred=1, status="Done",
         done_date=D(2026, 4, 17)),
    dict(phase="Pre-construction", task="Contractor selection", room="Whole house", dur=14,
         pred=1, status="Done", done_date=D(2026, 4, 3)),
    dict(phase="Pre-construction", task="Order long-lead items", room="Whole house", dur=7,
         pred=3, status="Done", done_date=D(2026, 4, 10)),
    dict(phase="Construction", task="Demolition & strip-out", room="Whole house",
         contractor="Hansen Demolition", dur=10, pred=2, status="Done",
         done_date=D(2026, 4, 29)),
    dict(phase="Construction", task="Structural beam & walls", room="Living room",
         contractor="Solid Structures Ltd", dur=12, pred=5, status="Done",
         done_date=D(2026, 5, 11)),
    dict(phase="Construction", task="Windows & doors", room="Whole house",
         contractor="ClearView Windows", dur=8, pred=5, status="Done",
         done_date=D(2026, 5, 8)),
    dict(phase="Construction", task="Plumbing rough-in", room="Bathroom 1",
         contractor="FlowRight Plumbing", dur=14, pred=6, delay=11, status="In progress"),
    dict(phase="Construction", task="Electrical rough-in", room="Whole house",
         contractor="Bright Spark Electric", dur=28, pred=6, delay=7, status="In progress"),
    dict(phase="Construction", task="Heat pump & ventilation", room="Whole house",
         contractor="ClimaHeat HVAC", dur=10, pred=8, status="Not started"),
    dict(phase="Construction", task="Rough-in inspection", room="Whole house", dur=2, pred=9,
         status="Not started"),
    dict(phase="Construction", task="Insulation & drywall", room="Whole house",
         contractor="Solid Structures Ltd", dur=14, pred=11, status="Not started"),
    dict(phase="Construction", task="Flooring", room="Living room",
         contractor="Oak & Plank Flooring", dur=10, pred=12, status="Not started"),
    dict(phase="Construction", task="Kitchen installation", room="Kitchen",
         contractor="Nordic Kitchens", dur=12, pred=12, status="Not started"),
    dict(phase="Construction", task="Bathroom 1 fit-out", room="Bathroom 1",
         contractor="Aqua Bath Studio", dur=15, pred=12, status="Not started"),
    dict(phase="Construction", task="Bathroom 2 fit-out", room="Bathroom 2",
         contractor="Aqua Bath Studio", dur=10, pred=15, status="Not started"),
    dict(phase="Construction", task="Painting & decorating", room="Whole house",
         contractor="Finish Line Painters", dur=12, pred=16, status="Not started"),
    dict(phase="Construction", task="Landscaping", room="Exterior", dur=10, pred=7,
         manual=D(2026, 7, 20), status="Not started"),
    dict(phase="Final", task="Final electrical & plumbing fixes", room="Whole house",
         contractor="Bright Spark Electric", dur=5, pred=17, status="Not started"),
    dict(phase="Final", task="Final inspection", room="Whole house", dur=2, pred=19,
         status="Not started"),
    dict(phase="Final", task="Punch list", room="Whole house", dur=10, pred=20,
         status="Not started"),
    dict(phase="Final", task="Cleaning", room="Whole house", dur=3, pred=21,
         status="Not started"),
    dict(phase="Final", task="Furniture & move-in", room="Whole house", dur=5, pred=22,
         status="Not started"),
]

# Typical sequence prefilled in the BLANK file (no dates, no contractors).
BLANK_TASKS = [
    dict(phase="Pre-construction", task="Design & plans", dur=21),
    dict(phase="Pre-construction", task="Building permit", dur=28, pred=1),
    dict(phase="Pre-construction", task="Contractor selection", dur=14, pred=1),
    dict(phase="Pre-construction", task="Order long-lead items", dur=7, pred=3),
    dict(phase="Construction", task="Demolition & strip-out", dur=10, pred=2),
    dict(phase="Construction", task="Structural works", dur=12, pred=5),
    dict(phase="Construction", task="Electrical rough-in", dur=14, pred=6),
    dict(phase="Construction", task="Plumbing rough-in", dur=14, pred=6),
    dict(phase="Construction", task="Rough-in inspection", dur=2, pred=8),
    dict(phase="Construction", task="Insulation & walls", dur=14, pred=9),
    dict(phase="Construction", task="Flooring", dur=10, pred=10),
    dict(phase="Construction", task="Kitchen installation", dur=12, pred=10),
    dict(phase="Construction", task="Bathroom fit-out", dur=15, pred=10),
    dict(phase="Construction", task="Painting & decorating", dur=12, pred=13),
    dict(phase="Final", task="Final inspection", dur=2, pred=14),
    dict(phase="Final", task="Punch list", dur=10, pred=15),
    dict(phase="Final", task="Cleaning", dur=3, pred=16),
    dict(phase="Final", task="Move-in", dur=3, pred=17),
]
for _t in BLANK_TASKS:
    _t["status"] = "Not started"

SELECTIONS = [
    dict(item="Kitchen worktop", room="Kitchen", cat="Kitchen", a_name="Quartz",
         a_price=2450, b_name="Laminate", b_price=890, c_name="Solid oak", c_price=1600,
         selected="A", reason="Durable, matches cabinet colour", supplier="StoneWorks",
         lead=21, task=14, ordered="Yes", order_date=D(2026, 6, 1),
         delivery=D(2026, 6, 26), delivered="No"),
    dict(item="Kitchen backsplash tiles", room="Kitchen", cat="Kitchen", a_name="White gloss",
         a_price=380, b_name="Zellige green", b_price=520, selected="A",
         reason="Budget", supplier="TileDepot", lead=10, task=14, ordered="No"),
    dict(item="Sink & tap", room="Kitchen", cat="Kitchen", a_name="Undermount + boiling tap",
         a_price=620, b_name="Inset + mixer", b_price=410, selected="A",
         reason="Daily convenience", supplier="TapHouse", lead=14, task=14, ordered="No"),
    dict(item="Oven", room="Kitchen", cat="Appliances", a_name="Pyrolytic oven", a_price=1150,
         b_name="Standard oven", b_price=890, selected="A", reason="Self-cleaning",
         supplier="ApplianceHub", lead=7, task=14, ordered="No"),
    dict(item="Fridge-freezer", room="Kitchen", cat="Appliances", a_name="Integrated 70/30",
         a_price=1390, selected="A", supplier="ApplianceHub", lead=7, task=14,
         ordered="Yes", order_date=D(2026, 5, 25), delivery=D(2026, 6, 2), delivered="Yes"),
    dict(item="Dishwasher", room="Kitchen", cat="Appliances", a_name="Silent 42dB",
         a_price=690, b_name="Standard", b_price=540, selected="A", reason="Open-plan noise",
         supplier="ApplianceHub", lead=7, task=14, ordered="Yes", order_date=D(2026, 6, 10),
         delivery=D(2026, 7, 8), delivered="No"),
    dict(item="Bathroom 1 floor & wall tiles", room="Bathroom 1", cat="Bathrooms",
         a_name="Grey porcelain 60x60", a_price=1450, b_name="Marble look", b_price=1980,
         selected="A", reason="Slip rating R10", supplier="TileDepot", lead=21, task=15,
         ordered="Yes", order_date=D(2026, 6, 4), delivery=D(2026, 6, 25), delivered="No"),
    dict(item="Bathroom 1 vanity unit", room="Bathroom 1", cat="Bathrooms",
         a_name="Oak 100cm double", a_price=890, b_name="Wall-hung 80cm", b_price=1240,
         selected="A", supplier="BathWorld", lead=28, task=15, ordered="Yes",
         order_date=D(2026, 5, 28), delivery=D(2026, 6, 30), delivered="No"),
    dict(item="Walk-in shower enclosure", room="Bathroom 1", cat="Bathrooms",
         a_name="Matt black 120cm", a_price=1150, b_name="Chrome 100cm", b_price=1600,
         selected="A", supplier="BathWorld", lead=14, task=15, ordered="Yes",
         order_date=D(2026, 5, 20), delivery=D(2026, 6, 5), delivered="Yes"),
    dict(item="Bathroom 2 tiles", room="Bathroom 2", cat="Bathrooms", a_name="Terrazzo",
         a_price=780, b_name="Subway white", b_price=1100, c_name="Hexagon grey",
         c_price=950, supplier="TileDepot", lead=21, task=16, ordered="No"),
    dict(item="Bathroom 2 toilet", room="Bathroom 2", cat="Bathrooms", a_name="Wall-hung",
         a_price=420, b_name="Close-coupled", b_price=560, supplier="BathWorld", lead=10,
         task=16, ordered="No"),
    dict(item="Living room flooring", room="Living room", cat="Flooring",
         a_name="Engineered oak", a_price=3900, b_name="Laminate oak look", b_price=1800,
         supplier="Oak & Plank Flooring", lead=28, task=13, ordered="No"),
    dict(item="Sofa", room="Living room", cat="Furniture", a_name="3-seater linen",
         a_price=2200, b_name="Corner sofa", b_price=1650, supplier="HomeStore", lead=42,
         need_in=D(2026, 9, 1), ordered="No"),
]

ISSUES = [
    dict(type="Issue", found=D(2026, 5, 14), room="Living room",
         desc="Rotten joist found under living room floor", resp="Solid Structures Ltd",
         sev="High", cost=1800, action="Engineer to confirm repair method",
         act_date=D(2026, 6, 12), status="Open"),
    dict(type="Issue", found=D(2026, 6, 3), room="Bathroom 1",
         desc="Waste pipe routed through planned shower niche", resp="FlowRight Plumbing",
         sev="Medium", cost=350, action="Site meeting to agree re-route",
         act_date=D(2026, 6, 17), status="In progress"),
    dict(type="Issue", found=D(2026, 6, 10), room="Kitchen",
         desc="Socket positions don't match kitchen plan", resp="Bright Spark Electric",
         sev="Medium", cost=250, action="Send marked-up plan to electrician",
         act_date=D(2026, 6, 11), status="Open"),
    dict(type="Punch item", found=D(2026, 5, 9), room="Master bedroom",
         desc="Window handle loose", resp="ClearView Windows", sev="Low", cost=0,
         action="Fix at final visit", act_date=D(2026, 6, 20), status="Open"),
    dict(type="Punch item", found=D(2026, 6, 15), room="Living room",
         desc="Scratch on new sliding door frame", resp="ClearView Windows", sev="Low", cost=0,
         action="Touch-up at final visit", act_date=D(2026, 6, 26), status="Open"),
    dict(type="Issue", found=D(2026, 4, 22), room="Whole house",
         desc="Asbestos in old floor tiles", resp="Hansen Demolition", sev="High", cost=1100,
         action="Licensed removal", act_date=D(2026, 4, 25), status="Resolved",
         res_date=D(2026, 4, 28)),
    dict(type="Issue", found=D(2026, 5, 5), room="Exterior",
         desc="Skip blocking neighbour's driveway", resp="Hansen Demolition", sev="Low",
         cost=0, action="Move skip", act_date=D(2026, 5, 6), status="Resolved",
         res_date=D(2026, 5, 6)),
]

VAULT = [
    dict(name="Architect contract", type="Contract", contractor="GreenPlan Architects",
         date=D(2026, 2, 20), link="https://drive.google.com/example-greenplan-contract"),
    dict(name="Design drawings rev C", type="Plan", contractor="GreenPlan Architects",
         date=D(2026, 3, 20), link="https://drive.google.com/example-plans"),
    dict(name="Building permit", type="Permit", date=D(2026, 4, 17),
         link="https://drive.google.com/example-permit"),
    dict(name="Hansen contract", type="Contract", contractor="Hansen Demolition",
         date=D(2026, 4, 5)),
    dict(name="Hansen insurance certificate", type="Insurance",
         contractor="Hansen Demolition", date=D(2026, 4, 5)),
    dict(name="Hansen quote", type="Quote", contractor="Hansen Demolition",
         date=D(2026, 3, 28)),
    dict(name="Solid Structures contract", type="Contract",
         contractor="Solid Structures Ltd", date=D(2026, 4, 12)),
    dict(name="Solid Structures insurance", type="Insurance",
         contractor="Solid Structures Ltd", date=D(2026, 4, 12)),
    dict(name="Solid Structures quote", type="Quote", contractor="Solid Structures Ltd",
         date=D(2026, 4, 1)),
    dict(name="FlowRight contract", type="Contract", contractor="FlowRight Plumbing",
         date=D(2026, 4, 20)),
    dict(name="FlowRight insurance", type="Insurance", contractor="FlowRight Plumbing",
         date=D(2026, 4, 20)),
    dict(name="FlowRight quote", type="Quote", contractor="FlowRight Plumbing",
         date=D(2026, 4, 2)),
    dict(name="Bright Spark contract", type="Contract", contractor="Bright Spark Electric",
         date=D(2026, 4, 22), notes="Insurance certificate still missing — asked twice"),
    dict(name="Bright Spark quote", type="Quote", contractor="Bright Spark Electric",
         date=D(2026, 4, 3)),
    dict(name="ClimaHeat contract", type="Contract", contractor="ClimaHeat HVAC",
         date=D(2026, 5, 2)),
    dict(name="ClimaHeat insurance", type="Insurance", contractor="ClimaHeat HVAC",
         date=D(2026, 5, 2)),
    dict(name="ClimaHeat quote", type="Quote", contractor="ClimaHeat HVAC",
         date=D(2026, 4, 15)),
    dict(name="ClearView contract", type="Contract", contractor="ClearView Windows",
         date=D(2026, 4, 1)),
    dict(name="ClearView insurance", type="Insurance", contractor="ClearView Windows",
         date=D(2026, 4, 1)),
    dict(name="ClearView quote", type="Quote", contractor="ClearView Windows",
         date=D(2026, 3, 22)),
    dict(name="Nordic Kitchens contract", type="Contract", contractor="Nordic Kitchens",
         date=D(2026, 5, 10)),
    dict(name="Nordic Kitchens insurance", type="Insurance", contractor="Nordic Kitchens",
         date=D(2026, 5, 10)),
    dict(name="Nordic Kitchens quote", type="Quote", contractor="Nordic Kitchens",
         date=D(2026, 4, 28)),
    dict(name="Aqua Bath contract", type="Contract", contractor="Aqua Bath Studio",
         date=D(2026, 5, 30)),
    dict(name="Aqua Bath quote", type="Quote", contractor="Aqua Bath Studio",
         date=D(2026, 5, 15)),
    dict(name="Aqua Bath insurance", type="Insurance", contractor="Aqua Bath Studio",
         date=D(2026, 5, 30)),
    dict(name="GreenPlan insurance", type="Insurance", contractor="GreenPlan Architects",
         date=D(2026, 2, 20)),
    dict(name="GreenPlan quote", type="Quote", contractor="GreenPlan Architects",
         date=D(2026, 2, 10)),
    dict(name="Structural beam inspection", type="Inspection",
         contractor="Solid Structures Ltd", room="Living room", stage="Rough-in",
         date=D(2026, 5, 11)),
    dict(name="Fridge-freezer receipt", type="Receipt", room="Kitchen", date=D(2026, 6, 2)),
]
for _room in ["Kitchen", "Bathroom 1", "Bathroom 2", "Master bedroom", "Living room",
              "Exterior"]:
    VAULT.append(dict(name=f"{_room} — before", type="Photo", room=_room, stage="Before",
                      date=D(2026, 3, 1), link="https://photos.google.com/example-album"))
for _room in ["Kitchen", "Bathroom 1", "Living room"]:
    VAULT.append(dict(name=f"{_room} — stripped out", type="Photo", room=_room,
                      stage="Demolition", date=D(2026, 4, 29)))
VAULT.append(dict(name="Kitchen — pipes & cables", type="Photo", room="Kitchen",
                  stage="Rough-in", date=D(2026, 6, 12)))

WARRANTIES = [
    dict(item="Roof repair (2019)", supplier="TopRoof", room="Exterior", start=D(2019, 9, 1),
         years=7),
    dict(item="Garage door motor", supplier="DoorTech", room="Exterior",
         start=D(2024, 6, 20), years=2),
    dict(item="Windows & doors", supplier="ClearView Windows", room="Whole house",
         start=D(2026, 5, 7), years=10, link="https://drive.google.com/example-warranty"),
    dict(item="Fridge-freezer", supplier="ApplianceHub", room="Kitchen", start=D(2026, 6, 2),
         years=2),
    dict(item="Demolition works", supplier="Hansen Demolition", room="Whole house",
         start=D(2026, 4, 29), years=1),
    dict(item="Structural beam", supplier="Solid Structures Ltd", room="Living room",
         start=D(2026, 5, 11), years=10),
]

MAINTENANCE = [
    dict(task="Service heating system", room="Whole house", freq=12, last=D(2025, 6, 10)),
    dict(task="Clean gutters", room="Exterior", freq=6, last=D(2026, 1, 15)),
    dict(task="Test smoke alarms", room="Whole house", freq=6, last=D(2026, 3, 1)),
    dict(task="Re-seal bathroom silicone", room="Bathroom 1", freq=24),
]

# Quote comparison blocks. checklist: {item index: (status, extra)}; default "Included".
def _chk(overrides):
    return overrides


QUOTES = [
    dict(cat="Kitchen", contractors=[
        dict(name="BudgetKitchen Co", price=16900, incl="Yes", weeks=3, warranty=2,
             refs="No", gut=2, valid=D(2026, 5, 15),
             chk={0: ("Not included", 600), 1: ("Not included", 350),
                  2: ("Not included", 450), 6: ("Unclear", 800), 7: ("Not included", 200),
                  9: ("Not included", 900), 10: ("Not included", 700),
                  11: ("Unclear", 0)}),
        dict(name="Nordic Kitchens", price=19400, incl="Yes", weeks=2, warranty=5,
             refs="Yes", gut=5, valid=D(2026, 5, 20), chk={}),
        dict(name="Kitchen World", price=18200, incl="No", weeks=4, warranty=3, refs="Yes",
             gut=3, valid=D(2026, 5, 30),
             chk={7: ("Unclear", 150), 9: ("Unclear", 400)}),
    ]),
    dict(cat="Flooring", contractors=[
        dict(name="Oak & Plank Flooring", price=8900, incl="Yes", weeks=2, warranty=10,
             refs="Yes", gut=4, valid=D(2026, 6, 19),
             chk={2: ("Unclear", 150), 6: ("Not included", 600)}),
        dict(name="FloorMasters", price=8200, incl="Yes", weeks=3, warranty=5, refs="No",
             gut=3, valid=D(2026, 7, 15),
             chk={1: ("Not included", 250), 2: ("Not included", 200),
                  6: ("Not included", 900), 7: ("Not included", 150), 11: ("Unclear", 0)}),
    ]),
    dict(cat="Painting", contractors=[
        dict(name="Finish Line Painters", price=4700, incl="Yes", weeks=2, warranty=2,
             refs="Yes", gut=4, valid=D(2026, 7, 31), chk={}),
        dict(name="ColourPro", price=5300, incl="Yes", weeks=2, warranty=1, refs="No", gut=3,
             valid=D(2026, 6, 26), chk={7: ("Unclear", 0)}),
    ]),
    dict(cat="Roofing", contractors=[
        dict(name="TopRoof", price=4950, incl="Yes", weeks=1, warranty=10, refs="Yes", gut=4,
             valid=D(2026, 8, 31), chk={}),
        dict(name="SkyHigh Roofing", price=5400, incl="Yes", weeks=1, warranty=5,
             refs="Yes", gut=3, valid=D(2026, 8, 31), chk={1: ("Unclear", 300)}),
    ]),
]

FRIDAY_NOTES = {
    "completed": "Electrical first fix 90% done; shower enclosure delivered.",
    "delayed": "Plumbing rough-in (pipe re-route) — now 10 days late.",
    "changed": "EV charger change order requested by electrician (pending).",
    "risk": "Kitchen install on 2 Jul depends on drywall — tight.",
    "next": "1) Decide bathroom 2 tiles  2) Pay FlowRight after re-route fixed  3) Chase electrician insurance",
}


# Lite has no Selections & Orders tab: big material suppliers are tracked as contractors.
LITE_SUPPLIERS = [
    dict(company="StoneWorks", trade="Quartz worktop (supply)", cat="Kitchen", room="Kitchen",
         contact="Order desk", phone="+31 20 555 0101", email="orders@stoneworks.example",
         value=2450, signed="Yes", start=D(2026, 6, 1), end=D(2026, 6, 26), insured="Yes",
         licensed="Yes", warranty=10, work=0.0),
    dict(company="ApplianceHub", trade="Kitchen appliances (supply)", cat="Appliances",
         room="Kitchen", contact="Web shop", phone="+31 20 555 0102",
         email="service@appliancehub.example", value=3230, signed="Yes", start=D(2026, 5, 25),
         end=D(2026, 7, 8), insured="Yes", licensed="Yes", warranty=2, work=0.4),
    dict(company="BathWorld", trade="Vanity + shower enclosure (supply)", cat="Bathrooms",
         room="Bathroom 1", contact="Showroom", phone="+31 20 555 0103",
         email="sales@bathworld.example", value=2040, signed="Yes", start=D(2026, 5, 20),
         end=D(2026, 6, 30), insured="Yes", licensed="Yes", warranty=5, work=0.55),
]


def contractors(lite=False):
    """Contractor rows for an edition. Lite has no Change Orders tab, so approved change
    orders are folded into the contract value (as a homeowner would do by hand)."""
    if not lite:
        return CONTRACTORS
    out = []
    for c in CONTRACTORS:
        extra = sum(x["cost"] for x in CHANGE_ORDERS
                    if x["contractor"] == c["company"] and x["status"] == "Approved")
        c = dict(c)
        if extra:
            c["value"] = (c.get("value") or 0) + extra
        out.append(c)
    return out + LITE_SUPPLIERS
